codecov:
  branch: main
  status:
    patch: off

ignore:
  - "python/adb_auto_player/games/**"
  - "python/adb_auto_player/game.py"
  - "python/adb_auto_player/adb.py"
  - "python/tests/**"
  - "app.go"
  - "main.go"
  - "app*.go"
  - "internal/processmanager.go"

flags:
  windows-latest:
    carryforward: true
  macos-latest:
    carryforward: true
