codecov:
  branch: main

ignore:
  - "python/adb_auto_player/games/**"
  - "python/tests/**"
  - "app.go"
  - "main.go"

flags:
  windows-latest:
    carryforward: true
  macos-latest:
    carryforward: true
