codecov:
  branch: main
  status:
    patch: off

ignore:
  - "python/adb_auto_player/games/**"
  - "python/adb_auto_player/game.py"
  - "python/adb_auto_player/adb.py"
  - "python/adb_auto_player/commands/**"
  - "python/tests/**"
  - "main.go"
  - "internal/app/**"
  - "internal/games/**"
  - "internal/hotkeys/**"
  - "internal/process/**"


flags:
  windows-latest:
    carryforward: true
  macos-latest:
    carryforward: true
