['Auto Play']
'Alliance Research & Gifts' = true
Build = true
'Collect Campaign Chest' = true
'Gather Resources' = ['Food', 'Wood', 'Stone', 'Gold']
'Recruit Troops' = true
Research = true
'Research Military First' = false
'Building Slot 2' = true
