['Auto Play']
'Alliance Gifts' = true
'Alliance Research' = true
'Build Slot 1' = true
'Build Slot 2' = true
'Collect Campaign Chest' = true
'Collect Free Scrolls' = true
'Gather Resources' = ['Food', 'Wood', 'Stone', 'Gold']
'Recruit Troops' = true
Research = false
'Research Military First' = false
'Purchase Seal of Solidarity' = false
'Skip Hold Position Check' = true
