['AFK Stages']
Attempts = 1
'Both Modes' = true
Formations = 7
Repeat = true
'Spend Gold' = false
'Suggested Formations' = true

["Dura's Trials"]
Attempts = 2
Formations = 7
'Spend Gold' = false
'Suggested Formations' = true

[General]
'Assist Limit' = 20
'Exclude Heroes' = []

['Legend Trial']
Attempts = 5
Formations = 7
'Spend Gold' = false
'Suggested Formations' = true
Towers = ['Lightbearer', 'Wilder', 'Graveborn', 'Mauler']
