['AFK Stages']
Attempts = 5
'Both Modes' = true
Formations = 7
Repeat = true
'Skip Manual Formations' = true
'Spend Gold' = true
'Suggested Formations' = true

['Arcane Labyrinth']
Difficulty = 13
'Key Quota' = 2700

[Dailies]
'Arena Battle' = true
'Buy All Affinity' = true
'Buy Discount Affinity' = true
'Single Pull' = true

['Dream Realm']
'Spend Gold' = true

["Dura's Trials"]
Attempts = 2
Formations = 7
'Spend Gold' = false
'Suggested Formations' = true

[General]
'Assist Limit' = 10
'Exclude Heroes' = []

['Legend Trial']
Attempts = 5
Formations = 7
'Spend Gold' = false
'Suggested Formations' = true
Towers = []

['My Custom Routine']
'Daily Tasks' = ['Season Talent Stages', 'AFK Stages', 'Season Talent Stages']
'Repeating Tasks' = ['Legend Trial', 'Season Talent Stages', 'AFK Stages']
'Skip Daily Tasks Today' = true
