["General"]
"Exclude Heroes" = []
"Assist Limit" = 20

["AFK Stages"]
Attempts = 5
Formations = 7
"Suggested Formations" = true
"Both Modes" = true
"Spend Gold" = false
Repeat = true

["Dura's Trials"]
Attempts = 2
Formations = 7
"Suggested Formations" = true
"Spend Gold" = false

["Legend Trial"]
Attempts = 5
Formations = 7
"Suggested Formations" = true
"Spend Gold" = false
Towers = ['Lightbearer', 'Wilder', 'Graveborn', 'Mauler']
