['AFK Stages']
Attempts = 5
'Both Modes' = true
Formations = 7
Repeat = true
'Spend Gold' = false
'Suggested Formations' = true

['Arcane Labyrinth']
Difficulty = 13

["Dura's Trials"]
Attempts = 2
Formations = 7
'Spend Gold' = false
'Suggested Formations' = true

[General]
'Assist Limit' = 10
'Exclude Heroes' = []

['Legend Trial']
Attempts = 5
Formations = 7
'Spend Gold' = false
'Suggested Formations' = true
Towers = ['Lightbearer', 'Wilder', 'Graveborn', 'Mauler']

['Dream Realm']
'Spend Gold' = true
