// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Changelog {
    "body": string;
    "version": string;

    /** Creates a new Changelog instance. */
    constructor($$source: Partial<Changelog> = {}) {
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Changelog instance from a string or object.
     */
    static createFrom($$source: any = {}): Changelog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Changelog($$parsedSource as Partial<Changelog>);
    }
}

export class UpdateInfo {
    "available": boolean;
    "version": string;
    "releaseURL": string;
    "downloadURL": string;
    "size": number;
    "autoUpdate": boolean;
    "disabled": boolean;
    "redirectToGitHub": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("releaseURL" in $$source)) {
            this["releaseURL"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("autoUpdate" in $$source)) {
            this["autoUpdate"] = false;
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }
        if (!("redirectToGitHub" in $$source)) {
            this["redirectToGitHub"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
