// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1249893213).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DownloadUpdate(downloadURL: string): $CancellablePromise<void> {
    return $Call.ByID(674014119, downloadURL);
}

export function GetChangelogs(): $CancellablePromise<$models.Changelog[]> {
    return $Call.ByID(241706445).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $models.Changelog.createFrom;
const $$createType2 = $Create.Array($$createType1);
