// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GameGUI {
    "game_title": string;
    "settings_file": string;
    "menu_options": MenuOption[];
    "categories"?: string[];
    "constraints": { [_: string]: any };

    /** Creates a new GameGUI instance. */
    constructor($$source: Partial<GameGUI> = {}) {
        if (!("game_title" in $$source)) {
            this["game_title"] = "";
        }
        if (!("settings_file" in $$source)) {
            this["settings_file"] = "";
        }
        if (!("menu_options" in $$source)) {
            this["menu_options"] = [];
        }
        if (!("constraints" in $$source)) {
            this["constraints"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameGUI instance from a string or object.
     */
    static createFrom($$source: any = {}): GameGUI {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("menu_options" in $$parsedSource) {
            $$parsedSource["menu_options"] = $$createField2_0($$parsedSource["menu_options"]);
        }
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField3_0($$parsedSource["categories"]);
        }
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField4_0($$parsedSource["constraints"]);
        }
        return new GameGUI($$parsedSource as Partial<GameGUI>);
    }
}

export class MenuOption {
    "label": string;
    "custom_label"?: string;
    "args": string[];
    "category"?: string;
    "tooltip"?: string;

    /** Creates a new MenuOption instance. */
    constructor($$source: Partial<MenuOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuOption instance from a string or object.
     */
    static createFrom($$source: any = {}): MenuOption {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        return new MenuOption($$parsedSource as Partial<MenuOption>);
    }
}

// Private type creation functions
const $$createType0 = MenuOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
