// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Exit(): $CancellablePromise<void> {
    return $Call.ByID(1324429835);
}

export function MinimizeToTray(): $CancellablePromise<void> {
    return $Call.ByID(1967520090);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3192583634);
}
