[adb]
host = '127.0.0.1'
port = 5037

[device]
ID = '127.0.0.1:5555'
wm_size = false
streaming = true

[logging]
level = 'INFO'
debug_save_screenshots = 60
action_log_limit = 10

[ui]
theme = 'terminus'
