// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ipc$0 from "../ipc/models.js";

export function Debug(): $CancellablePromise<void> {
    return $Call.ByID(2279654713);
}

export function GetGameGUI(): $CancellablePromise<ipc$0.GameGUI | null> {
    return $Call.ByID(1729333075).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetGameSettingsForm(game: ipc$0.GameGUI): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(3164261351, game).then(($result: any) => {
        return $$createType2($result);
    });
}

export function KillGameProcess(): $CancellablePromise<void> {
    return $Call.ByID(4018216029);
}

export function SaveDebugZip(): $CancellablePromise<void> {
    return $Call.ByID(2087350553);
}

export function SaveGameSettings(gameSettings: { [_: string]: any }): $CancellablePromise<ipc$0.GameGUI | null> {
    return $Call.ByID(3663949236, gameSettings).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartGameProcess(args: string[]): $CancellablePromise<void> {
    return $Call.ByID(2571463401, args);
}

// Private type creation functions
const $$createType0 = ipc$0.GameGUI.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
