name: Setup Tools
description: Installs Node.js, uv, and Python, either all at once or a specific tool
inputs:
  tool:
    description: 'The tool to set up (rust, node, uv-python, or all)'
    required: false
    default: 'all'
  node-version:
    description: 'Node.js version to install'
    default: 'latest'
  uv-version:
    description: 'uv version to install'
    default: '0.7.11'
  python-version:
    description: 'Python version to install'
    default: '3.14'
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "latest"
    - name: Setup Node
      if: inputs.tool == 'all'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Install uv
      if: inputs.tool == 'all' || inputs.tool == 'uv-python'
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
    - name: Set up Python
      if: inputs.tool == 'all' || inputs.tool == 'uv-python'
      run: |
        uv python install ${{ inputs.python-version }}
      shell: bash
