// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAdbAutoPlayerSettings(): $CancellablePromise<$models.AdbAutoPlayerSettings> {
    return $Call.ByID(428526674).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAdbAutoPlayerSettingsForm(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(931154948).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSettingsDirPath(): $CancellablePromise<string> {
    return $Call.ByID(3505840555);
}

/**
 * LoadSettings reloads the general settings
 */
export function LoadAdbAutoPlayerSettings(): $CancellablePromise<$models.AdbAutoPlayerSettings> {
    return $Call.ByID(2237809018).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveAdbAutoPlayerSettings(settings: $models.AdbAutoPlayerSettings): $CancellablePromise<void> {
    return $Call.ByID(601590237, settings);
}

// Private type creation functions
const $$createType0 = $models.AdbAutoPlayerSettings.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
