// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAdbAutoPlayerSettings returns the current general settings
 * @returns {$CancellablePromise<$models.AdbAutoPlayerSettings>}
 */
export function GetAdbAutoPlayerSettings() {
    return $Call.ByID(428526674).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetAdbAutoPlayerSettingsForm() {
    return $Call.ByID(931154948).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetSettingsDirPath() {
    return $Call.ByID(3505840555);
}

/**
 * LoadSettings reloads the general settings
 * @returns {$CancellablePromise<$models.AdbAutoPlayerSettings>}
 */
export function LoadAdbAutoPlayerSettings() {
    return $Call.ByID(2237809018).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.AdbAutoPlayerSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveAdbAutoPlayerSettings(settings) {
    return $Call.ByID(601590237, settings);
}

// Private type creation functions
const $$createType0 = $models.AdbAutoPlayerSettings.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
