[tool.poetry]
name = "adb-auto-player"
version = "0.0.0"
description = ""
authors = ["yulesxoxo <https://github.com/yulesxoxo/yulesxoxo>"]
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
pillow = "^11.0.0"
adbutils = "^2.8.0"
opencv-python = "^4.10.0.84"
pydantic = "^2.10.5"

[tool.poetry.group.dev.dependencies]
nuitka = "^2.5.9"
pytest = "^8.3.4"

[tool.black]
line-length = 88
target-version = ['py312']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
adb-auto-player = "adb_auto_player.main:main"
