name: Build

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: npm version tag_name
        if: github.event_name == 'release' && github.event.action == 'published'
        working-directory: frontend
        run: npm version "${{ github.event.release.tag_name }}"

      - name: npm install
        working-directory: frontend
        run: npm install

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: python -m pip install uv

      - name: uv version
        if: github.event_name == 'release' && github.event.action == 'published'
        working-directory: python
        run: uv version ${{ github.event.release.tag_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Wails3
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Build with version (release)
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: pwsh
        run: .github/scripts/build_windows.ps1 -Version "${{ github.event.release.tag_name }}"

      - name: Build without version (manual)
        if: github.event_name == 'workflow_dispatch'
        shell: pwsh
        run: .github/scripts/build_windows.ps1

      - name: Zip output
        shell: pwsh
        run: .github/scripts/zip_windows.ps1

      - name: Release Windows artifact
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: AdbAutoPlayer_Windows.zip

      - name: Upload Windows artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: AdbAutoPlayer_Windows.zip
          path: AdbAutoPlayer/[!.]*

  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: npm version tag_name
        if: github.event_name == 'release' && github.event.action == 'published'
        working-directory: frontend
        run: npm version "${{ github.event.release.tag_name }}"

      - name: npm install
        working-directory: frontend
        run: npm install

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: python -m pip install uv

      - name: uv version
        if: github.event_name == 'release' && github.event.action == 'published'
        working-directory: python
        run: uv version ${{ github.event.release.tag_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Wails3
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Make build_macos.sh executable
        run: chmod +x .github/scripts/build_macos.sh

      - name: Build with version (release)
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: bash
        run: VERSION="${{ github.event.release.tag_name }}" .github/scripts/build_macos.sh

      - name: Build without version (manual)
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: .github/scripts/build_macos.sh

      - name: Zip macOS artifact
        if: github.event_name == 'workflow_dispatch'
        run: |
          zip -r AdbAutoPlayer.app.zip AdbAutoPlayer.app
        shell: bash

      - name: Release macOS artifact
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: AdbAutoPlayer.app

      - name: Upload macOS artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: AdbAutoPlayer.app
          path: AdbAutoPlayer.app

  publish:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && !contains(github.event.release.tag_name, 'alpha')

    steps:
      - uses: actions/checkout@v4

      - name: Mark release as latest
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method PATCH \
            "/repos/${{ github.repository }}/releases/${{ github.event.release.id }}" \
            -f make_latest=true
