name: Tests - Go

on:
  pull_request:
  push:
    branches:
      - "*"
    paths-ignore:
      - 'frontend/**'
      - 'docs/**'
      - 'python/**'
  workflow_dispatch:

jobs:
  go-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Ensure frontend/build directory exists
        shell: bash
        run: mkdir -p frontend/build

      - name: Run Go tests
        run: |
          go test -v ./...
