name: Tests - Go

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-test.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build/**'
      - 'config/**'
      - 'internal/**'
      - 'wails.json'
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-test.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build/**'
      - 'config/**'
      - 'internal/**'
      - 'wails.json'
  workflow_dispatch:

jobs:
  go-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Ensure frontend/build directory exists and is embeddable
        shell: bash
        run: mkdir -p frontend/build && touch frontend/build/.gitignore

      - name: Run Go tests
        run: |
          go test -v ./...
