name: GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - '**/mdbook.yml'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: install mdbook-alerts preprocessor
        run: |
          tag=$(curl 'https://api.github.com/repos/lambdalisue/rs-mdbook-alerts/releases/latest' | jq -r '.tag_name')
          url="https://github.com/lambdalisue/rs-mdbook-alerts/releases/download/${tag}/mdbook-alerts-x86_64-unknown-linux-gnu"
          curl -sSL $alerts_url -o ./mdbook_alerts
          chmod +x ./mdbook_alerts
          echo `pwd`/mdbook_alerts >> $GITHUB_PATH

      - name: Run mdbook-alerts preprocessor
        run: |
          cd docs
          mdbook build

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/book'
      - uses: actions/deploy-pages@v4
        id: deployment
