name: Build on Release

on:
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            zip_files: "AdbAutoPlayer_Windows.zip,Patch_Windows.zip"

    permissions:
      contents: write
      id-token: write

    env:
      NUITKA_CACHE_DIR: ${{ github.action_path }}/nuitka/cache
      PYTHON_VERSION: '3.12'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: npm version tag_name
        run: |
            cd cmd/wails/frontend
            npm version "${{ github.event.release.tag_name }}"

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install poetry
        run: python -m pip install poetry

      - name: poetry version tag_name
        run: |
          cd python
          poetry version "${{ github.event.release.tag_name }}"

      - name: install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: npm install
        run: |
          cd cmd/wails/frontend
          npm install

      - name: wails build
        run: |
          cd cmd/wails
          wails build -devtools

      - uses: actions/cache@v4
        with:
          path: ${{ env.NUITKA_CACHE_DIR }}
          key: ${{ runner.os }}-${{ runner.arch }}-python-${{ env.PYTHON_VERSION }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-python-${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-${{ runner.arch }}-python-
            ${{ runner.os }}-${{ runner.arch }}-

      - name: poetry run nuitka
        run: |
          cd python
          poetry install
          poetry run nuitka --standalone `
            --onefile `
            --output-filename=adb_auto_player.exe `
            --assume-yes-for-downloads `
            --windows-console-mode=disable `
            adb_auto_player/main.py

      - name: build_zip.ps1
        shell: pwsh
        run: .github/scripts/build_zip.ps1

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.zip_files }}
