name: Build on Release

on:
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            zip_files: "AdbAutoPlayer_Windows.zip"
            gui_zip_command: "Compress-Archive -Path .\\dist\\* -DestinationPath AdbAutoPlayer_Windows.zip"
          - os: macos-latest
            zip_files: "AdbAutoPlayer_MacOS.zip"
            gui_zip_command: |
              cd dist
              zip -r ../AdbAutoPlayer_MacOS.zip .

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      run: |
        python -m pip install poetry

    - name: Update version in pyproject.toml with release tag name
      run: |
        poetry version "${{ github.event.release.tag_name }}"

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Build the frontend
      run: |
        cd adb_auto_player/frontend
        pnpm install
        pnpm build --minify false

    - name: Create the GUI executable
      run: |
        poetry install
        poetry run pyinstaller --clean gui.spec

    - name: Zip the GUI dist directory
      run: ${{ matrix.gui_zip_command }}

    - name: Upload the ZIP to the release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.zip_files }}
