name: Build on Release

on:
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            zip_file: "AdbAutoPlayer_Windows.zip"
            spec_file: "windows.spec"
            zip_command: "Compress-Archive -Path .\\dist\\* -DestinationPath ${{ matrix.zip_file }}"
          - os: macos-latest
            zip_file: "AdbAutoPlayer_MacOS.zip"
            spec_file: "macos.spec"
            zip_command: |
              cd dist
              zip -r ../${{ matrix.zip_file }} .

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      run: |
        python -m pip install poetry

    - name: Update version in pyproject.toml with release tag name
      run: |
        poetry version "${{ github.event.release.tag_name }}"

    - name: Create the executable
      run: |
        poetry install
        poetry run pyinstaller --clean ${{ matrix.spec_file }}
        cp adb_auto_player/main_config.toml dist
        cp -r adb_auto_player/plugins dist/

    - name: Zip the dist directory
      run: ${{ matrix.zip_command }}

    - name: Upload the ZIP to the release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.zip_file }}
