// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window["go"]["main"]["App"]["CheckForUpdates"]();
}

export function Debug() {
  return window["go"]["main"]["App"]["Debug"]();
}

export function DownloadUpdate(arg1) {
  return window["go"]["main"]["App"]["DownloadUpdate"](arg1);
}

export function GetChangelogs() {
  return window["go"]["main"]["App"]["GetChangelogs"]();
}

export function GetEditableGameSettings(arg1) {
  return window["go"]["main"]["App"]["GetEditableGameSettings"](arg1);
}

export function GetEditableGeneralSettings() {
  return window["go"]["main"]["App"]["GetEditableGeneralSettings"]();
}

export function GetRunningSupportedGame(arg1) {
  return window["go"]["main"]["App"]["GetRunningSupportedGame"](arg1);
}

export function GetUISettings() {
  return window["go"]["main"]["App"]["GetUISettings"]();
}

export function IsGameProcessRunning() {
  return window["go"]["main"]["App"]["IsGameProcessRunning"]();
}

export function RegisterGlobalHotkeys() {
  return window["go"]["main"]["App"]["RegisterGlobalHotkeys"]();
}

export function SaveDebugZip() {
  return window["go"]["main"]["App"]["SaveDebugZip"]();
}

export function SaveGameSettings(arg1) {
  return window["go"]["main"]["App"]["SaveGameSettings"](arg1);
}

export function SaveGeneralSettings(arg1) {
  return window["go"]["main"]["App"]["SaveGeneralSettings"](arg1);
}

export function Shutdown(arg1) {
  return window["go"]["main"]["App"]["Shutdown"](arg1);
}

export function StartGameProcess(arg1) {
  return window["go"]["main"]["App"]["StartGameProcess"](arg1);
}

export function Startup(arg1) {
  return window["go"]["main"]["App"]["Startup"](arg1);
}

export function TerminateGameProcess() {
  return window["go"]["main"]["App"]["TerminateGameProcess"]();
}
