// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { updater } from "../models";
import { ipc } from "../models";
import { config } from "../models";
import { context } from "../models";

export function CheckForUpdates(): Promise<updater.UpdateInfo>;

export function Debug(): Promise<void>;

export function DownloadUpdate(arg1: string): Promise<void>;

export function GetChangelogs(): Promise<Array<updater.Changelog>>;

export function GetEditableGameSettings(
  arg1: ipc.GameGUI,
): Promise<Record<string, any>>;

export function GetEditableGeneralSettings(): Promise<Record<string, any>>;

export function GetRunningSupportedGame(arg1: boolean): Promise<ipc.GameGUI>;

export function GetUISettings(): Promise<config.UIConfig>;

export function IsGameProcessRunning(): Promise<boolean>;

export function RegisterGlobalHotkeys(): Promise<void>;

export function SaveDebugZip(): Promise<void>;

export function SaveGameSettings(arg1: Record<string, any>): Promise<void>;

export function SaveGeneralSettings(arg1: config.MainConfig): Promise<void>;

export function Shutdown(arg1: context.Context): Promise<void>;

export function StartGameProcess(arg1: Array<string>): Promise<void>;

export function Startup(arg1: context.Context): Promise<void>;

export function TerminateGameProcess(): Promise<void>;
